apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    name: admin
  - port: 32000
    nodePort: 32000
    protocol: TCP
    name: jdbc
  selector:
    app: haproxy
